# 定时重新部署，国际时间0点
on:
  push:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to LeanEngine
        uses: enflo/curl-action@v1.2
        with:
          curl: -X POST https://console.leancloud.app/1.1/engine/groups/web/production/version?gitTag=master&token=${{ secrets.DEPLOY_TOKEN }}
